import dns from 'node:dns'; import fs from 'node:fs';
dns.setDefaultResultOrder('ipv4first');
const TOKEN = fs.readFileSync('C:/Users/31534/Desktop/qdii-pages/.ghtoken', 'utf8').trim();
const H = { 'Authorization': 'Bearer ' + TOKEN, 'Accept': 'application/vnd.github+json', 'User-Agent': 'qdii-board' };
const r = await fetch('https://api.github.com/repos/a3153423343-crypto/qdii-pages/actions/runs?per_page=4', { headers: H, signal: AbortSignal.timeout(30000) });
const j = await r.json();
for (const w of (j.workflow_runs || [])) console.log('#' + w.run_number + ' ' + w.event.padEnd(13) + ' ' + w.status + '/' + (w.conclusion || '-'));
const BASE = 'https://a3153423343-crypto.github.io/qdii-pages/';
const d = await (await fetch(BASE + 'limits.json', { cache: 'no-store', signal: AbortSignal.timeout(30000) })).json();
console.log('线上数据 ' + d.generatedAt + ' | 实时 ' + d.liveCodes + ' 只 | ' + JSON.stringify(d.stats));
